micronaut:
  application:
    name: complete
#tag::application[]
---
application:
  max: 50
    #end::application[]
#tag::datasource[]
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://192.168.99.100:5432/micronaut`}
    username: ${JDBC_USER:dbuser}
    password: ${JDBC_PASSWORD:theSecretPassword}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
#end::datasource[]
#tag::jpa[]
---
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut.domain' # <1>
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]
